version: 2.1
description: # Reusable Plugin Pipeline

jobs:
  build_nodejs:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install yarn
          command: |
            sudo npm install -g yarn --quiet
            yarn install --pure-lockfile
      - run:
          name: Run Toolkit Build
          command: 'npx grafana-toolkit plugin:ci-build'
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - ci

  build_backend:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install yarn
          command: |
            sudo npm install -g yarn --quiet
            yarn install --pure-lockfile
      - run:
          name: Run Toolkit CI
          command: 'npx grafana-toolkit plugin:ci-build --platform XXX'
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - ci

  bundle:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Bundle Distribution
          command: 'npx grafana-toolkit plugin:ci-bundle'
      - persist_to_workspace:
          root: .
          paths:
            - ci
      - store_artifacts:
          path: ci

  test_master:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Grafana (local install)
          command: |
            wget https://dl.grafana.com/oss/release/grafana_6.2.5_amd64.deb
            sudo cp ci/grafana-test-env/custom.ini /etc/grafana/grafana.ini
            sudo apt-get install -y adduser libfontconfig1
            sudo dpkg -i grafana_6.2.5_amd64.deb
            sudo service grafana-server start
            grafana-cli --version

      - run:
          name: Run e2e tests
          command: |
            npx grafana-toolkit plugin:ci-test
      - persist_to_workspace:
          root: .
          paths:
            - ci

  test_latest:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Toolkit CI
          command: 'echo TODO...'

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Toolkit Deploy
          command: 'npx grafana-toolkit plugin:ci-deploy'
      - store_artifacts:
          path: ci


workflows:
  version: 2
  build_bundle_test_deploy:
    jobs:
      - build_nodejs
      - build_backend
      - bundle:
          requires:
            - build_nodejs
            - build_backend
      - test_master:
          requires:
            - bundle
      - test_latest:
          requires:
            - bundle
      - deploy:
          requires:
            - test_master
            - test_latest
