version: 2.1
description: # Reusable Plugin Pipeline

jobs:
  build_frontend:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install yarn
          command: |
            sudo npm install -g yarn --quiet
            yarn install --pure-lockfile
      - run:
          name: Run Toolkit Build
          command: 'npx grafana-toolkit plugin:ci-build'
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*
            - work/*

  build_backend:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install yarn
          command: |
            sudo npm install -g yarn --quiet
            yarn install --pure-lockfile
      - run:
          name: Run Toolkit CI
          command: 'npx grafana-toolkit plugin:ci-build --platform XXX'
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*
            - work/*

  bundle:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Bundle Distribution
          command: 'npx grafana-toolkit plugin:ci-bundle'
      - persist_to_workspace:
          root: .
          paths:
            - work/*
      - store_artifacts:
          path: work/artifacts

  test_master:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Grafana
          command: |
            npx grafana-toolkit plugin:ci-setup --installer grafana_6.2.5_amd64.deb
      - run:
          name: Run e2e tests
          command: |
            npx grafana-toolkit plugin:ci-test
      - persist_to_workspace:
          root: .
          paths:
            - work/*

  test_latest:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Toolkit CI
          command: 'echo TODO...'

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/plugin
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Toolkit Deploy
          command: 'npx grafana-toolkit plugin:ci-deploy'
      - store_artifacts:
          path: work


workflows:
  version: 2
  build_bundle_test_deploy:
    jobs:
      - build_frontend
      - build_backend
      - bundle:
          requires:
            - build_frontend
            - build_backend
      - test_master:
          requires:
            - bundle
      - test_latest:
          requires:
            - bundle
      - deploy:
          requires:
            - test_master
            - test_latest
